###
POST http://localhost:4000/api/v1/menu/
Content-type: application/json

{
    "name": "Menu 1",
    "slider_imgs": ["https://i.blogs.es/87930e/comidas-ricas/840_560.jpg", 
    "https://www.cocinacaserayfacil.net/wp-content/uploads/2020/03/Platos-de-comida-que-pides-a-domicilio-y-puedes-hacer-en-casa-945x630.jpg",
    "https://www.recetasnestle.com.co/sites/default/files/2022-06/ingredientes-comida-de-mar-parrilla.jpg"],
    "categories": [],
    "places": ["6470ce35bedff07c5cc81fbe"]
}

###
GET http://localhost:4000/api/v1/menu/

###
GET http://localhost:4000/api/v1/menu/6470ce35bedff07c5cc81fbe

